### ISSUE TITLE
Import issue: Module not found: Error: Can't resolve 'react-addons-css-transition-group'

### ISSUE THREAD

**Issue by anoush-soghomonyan** [Grace951/react-image-carousel#1]
When I'm trying to import module it gives this.

ERROR in ./node_modules/react-image-carousel/lib/ReactImageCarousel.js
Module not found: Error: Can't resolve 'react-addons-css-transition-group' in 'C:\project\node_modules\react-image-carousel\lib'

**Comment by andrewnguyen22** [comment]
Same Here

**Comment by marionjudy13** [comment]
If you run "npm install --save react-addons-css-transition-group", and then re-yarn that should fix it!  I had the same issue.

**Comment by francisco-jimenez** [comment]
TWIMC:  react-addons-css-transition-group The code in this package has moved
Check this out: 
https://www.npmjs.com/package/react-addons-css-transition-group

**Comment by francisco-jimenez** [comment]
> you run "npm install --save react-addons-css-transition-group", and then re-yarn that should fix it! I had the same issue.

I did that and still getting an error 

TypeError: Cannot read property 'array' of undefined
./node_modules/react-image-carousel/lib/Footer.js
node_modules/react-image-carousel/lib/Footer.js:86
  83 | }(_react2.default.Component);
  84 | 
  85 | Footer.propTypes = {
--> 86 | 	images: _react2.default.PropTypes.array.isRequired,
  87 | 	thumb: _react2.default.PropTypes.bool,
  88 | 	currentId: _react2.default.PropTypes.number,
  89 | 	setCurrent: _react2.default.PropTypes.func.isRequired

**Comment by Grace951** [comment]
Fix in V2.0.18.
I have updated to react 16 on react-image-carousel V2.0.18
react-image-carousel V1  is for react 15
react-image-carousel V2  is for react 16
